import { OnGatewayConnection, OnGatewayDisconnect, OnGatewayInit } from '@nestjs/websockets';
import { Server, Socket } from 'socket.io';
import { TaskQueue } from 'src/database/models/task-queue.model';
import { Tenant } from 'src/database/models/tenant.model';
import { PostgresProvider } from 'src/database/postgres.provider';
import { AppLoggerService } from '../logger/logger.service';
import { TokenProvider } from '../utility/token.provider';
import { ConnectionSubscribeEventData } from './types/connection-event.type';
import { ConnectionTaskAcceptData, ConnectionTaskDoneData, ConnectionTaskRejectData, DispatchTaskData } from './types/connection-task.type';
export declare class SocketGateway implements OnGatewayConnection, OnGatewayDisconnect, OnGatewayInit {
    private readonly logger;
    private readonly tokenProvider;
    private readonly postgresProvider;
    private readonly tenantRepository;
    private readonly taskQueueRepository;
    private connections;
    private events;
    constructor(logger: AppLoggerService, tokenProvider: TokenProvider, postgresProvider: PostgresProvider, tenantRepository: typeof Tenant, taskQueueRepository: typeof TaskQueue);
    afterInit(server: Server): void;
    handleConnection(client: Socket): Promise<void>;
    handleDisconnect(client: Socket): void;
    handleTaskAccepted(client: Socket, data: ConnectionTaskAcceptData): Promise<void>;
    handleTaskRejected(client: Socket, data: ConnectionTaskRejectData): Promise<void>;
    handleTaskDone(client: Socket, data: ConnectionTaskDoneData): Promise<void>;
    handleEventSubscribe(client: Socket, data: ConnectionSubscribeEventData): Promise<void>;
    handleEventUnsubscribe(client: Socket, data: ConnectionSubscribeEventData): Promise<void>;
    dispatchTask(taskId: string, tenantId: string, dispatchTaskData?: DispatchTaskData): Promise<string | undefined>;
    sendEvent(eventName: string, payload: any): Promise<void>;
    subscribeClientToEvent(clientId: string, eventName: string): void;
    unsubscribeClientToEvent(clientId: string, eventName: string): void;
    private getAvailableBot;
}
