# PENTING: RENAME config.example.toml JADI config.toml
# tanda pagar (#) adalah komentar, hilangkan # jika ingin dijalankan atau tambahkan pagar jika tidak ingin dijalankan

# Volve Capital Auth
appId = "ganti_dengan_id_dari_volve_capital"
appSecret = "ganti_dengan_secret_yang_sesuai_app_id"

# Timeout Pengecekan Elemen di Browser (dalam milidetik)
timeout = 45000
# Jumlah Pengulangan proses bot jika gagal
max_retry_attempt = 3
# Waktu Loading acak (agar terlihat seperti manusia bukan bot)
# minimal dan maksimal waktu dalam milidetik
min_wait_time_ms = 10000
max_wait_time_ms = 60000
# Jumlah proses yang bisa dikerjakan bersamaan
concurrency = 2

# Informasi Seller Shopee yang akan diproses
[[shopee_shop]]
name = "ganti_dengan_nama_toko"
loginKey = "ganti_dengan_loginKey_toko"
password = "ganti_dengan_password_toko"

# [[shopee_shop]]
# name = "contoh_toko_kedua"
# loginKey = "contoh_toko_kedua"
# password = "contoh_toko_kedua"

# TEMPLATE CHAT YANG AKAN DIKIRIM DI CHAT SHOPEE
# Chat yang dikirim sebelum mengirim template akun
[[chat_template.send_before]]
message = """
❗️RULES NTFLIX (WAJIB BACA)❗️

1. Hanya untuk 1 Device (ganti device tidak ada garansi)
2. Dilarang Mengubah/menggunakan profile yang bukan miliknya
3. Dilarang Mengubah Apapun (termasuk pin, nama profile dan password)
4. Melanggar :  GARANSI HANGUS
"""

# [[chat_template.send_before]]
# message = """
# CONTOH CHAT SEBELUM TEMPLATE AKUN KEDUA
# """

# Chat yang dikirim setelah mengirim template akun
[[chat_template.send_after]]
message = """
Tolong Bantu Ulasan bintang 5 ya kak :) ⭐️⭐️⭐️⭐️⭐

--------THANK YOU--------
"""

# [[chat_template.send_after]]
# message = """
# CONTOH CHAT SETELAH TEMPLATE AKUN KEDUA
# """

# Chat yang dikirim jika proses gagal
[[chat_template.send_fallback]]
message = "Pesanan kaka sudah kami terima dan akan kami proses segera, mohon ditunggu 🔁"

# [[chat_template.send_fallback]]
# message = "Contoh Fallbac Kedua"
