packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - better-sqlite3
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - sharp
  - unrs-resolver
  - workerd
