/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTransactionIndexRouteImport } from './routes/dashboard/transaction/index'
import { Route as DashboardProductIndexRouteImport } from './routes/dashboard/product/index'
import { Route as DashboardPlatformProductIndexRouteImport } from './routes/dashboard/platform-product/index'
import { Route as DashboardLogsIndexRouteImport } from './routes/dashboard/logs/index'
import { Route as DashboardEmailIndexRouteImport } from './routes/dashboard/email/index'
import { Route as DashboardAccountIndexRouteImport } from './routes/dashboard/account/index'
import { Route as DashboardTransactionCreateRouteImport } from './routes/dashboard/transaction/create'
import { Route as DashboardProductCreateRouteImport } from './routes/dashboard/product/create'
import { Route as DashboardPlatformProductCreateRouteImport } from './routes/dashboard/platform-product/create'
import { Route as DashboardPlatformProductIdRouteImport } from './routes/dashboard/platform-product/$id'
import { Route as DashboardEmailCreateRouteImport } from './routes/dashboard/email/create'
import { Route as DashboardEmailIdRouteImport } from './routes/dashboard/email/$id'
import { Route as DashboardAccountCreateRouteImport } from './routes/dashboard/account/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionIndexRoute =
  DashboardTransactionIndexRouteImport.update({
    id: '/transaction/',
    path: '/transaction/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductIndexRoute = DashboardProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlatformProductIndexRoute =
  DashboardPlatformProductIndexRouteImport.update({
    id: '/platform-product/',
    path: '/platform-product/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardLogsIndexRoute = DashboardLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailIndexRoute = DashboardEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountIndexRoute = DashboardAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTransactionCreateRoute =
  DashboardTransactionCreateRouteImport.update({
    id: '/transaction/create',
    path: '/transaction/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardProductCreateRoute = DashboardProductCreateRouteImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardPlatformProductCreateRoute =
  DashboardPlatformProductCreateRouteImport.update({
    id: '/platform-product/create',
    path: '/platform-product/create',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardPlatformProductIdRoute =
  DashboardPlatformProductIdRouteImport.update({
    id: '/platform-product/$id',
    path: '/platform-product/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardEmailCreateRoute = DashboardEmailCreateRouteImport.update({
  id: '/email/create',
  path: '/email/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardEmailIdRoute = DashboardEmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountCreateRoute = DashboardAccountCreateRouteImport.update({
  id: '/account/create',
  path: '/account/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/logs': typeof DashboardLogsIndexRoute
  '/dashboard/platform-product': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product': typeof DashboardProductIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account': typeof DashboardAccountIndexRoute
  '/dashboard/email': typeof DashboardEmailIndexRoute
  '/dashboard/logs': typeof DashboardLogsIndexRoute
  '/dashboard/platform-product': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product': typeof DashboardProductIndexRoute
  '/dashboard/transaction': typeof DashboardTransactionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/account/create': typeof DashboardAccountCreateRoute
  '/dashboard/email/$id': typeof DashboardEmailIdRoute
  '/dashboard/email/create': typeof DashboardEmailCreateRoute
  '/dashboard/platform-product/$id': typeof DashboardPlatformProductIdRoute
  '/dashboard/platform-product/create': typeof DashboardPlatformProductCreateRoute
  '/dashboard/product/create': typeof DashboardProductCreateRoute
  '/dashboard/transaction/create': typeof DashboardTransactionCreateRoute
  '/dashboard/account/': typeof DashboardAccountIndexRoute
  '/dashboard/email/': typeof DashboardEmailIndexRoute
  '/dashboard/logs/': typeof DashboardLogsIndexRoute
  '/dashboard/platform-product/': typeof DashboardPlatformProductIndexRoute
  '/dashboard/product/': typeof DashboardProductIndexRoute
  '/dashboard/transaction/': typeof DashboardTransactionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/account/create'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account'
    | '/dashboard/email'
    | '/dashboard/logs'
    | '/dashboard/platform-product'
    | '/dashboard/product'
    | '/dashboard/transaction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/dashboard/account/create'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account'
    | '/dashboard/email'
    | '/dashboard/logs'
    | '/dashboard/platform-product'
    | '/dashboard/product'
    | '/dashboard/transaction'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/'
    | '/dashboard/account/create'
    | '/dashboard/email/$id'
    | '/dashboard/email/create'
    | '/dashboard/platform-product/$id'
    | '/dashboard/platform-product/create'
    | '/dashboard/product/create'
    | '/dashboard/transaction/create'
    | '/dashboard/account/'
    | '/dashboard/email/'
    | '/dashboard/logs/'
    | '/dashboard/platform-product/'
    | '/dashboard/product/'
    | '/dashboard/transaction/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transaction/': {
      id: '/dashboard/transaction/'
      path: '/transaction'
      fullPath: '/dashboard/transaction'
      preLoaderRoute: typeof DashboardTransactionIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/': {
      id: '/dashboard/product/'
      path: '/product'
      fullPath: '/dashboard/product'
      preLoaderRoute: typeof DashboardProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/': {
      id: '/dashboard/platform-product/'
      path: '/platform-product'
      fullPath: '/dashboard/platform-product'
      preLoaderRoute: typeof DashboardPlatformProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/logs/': {
      id: '/dashboard/logs/'
      path: '/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/': {
      id: '/dashboard/email/'
      path: '/email'
      fullPath: '/dashboard/email'
      preLoaderRoute: typeof DashboardEmailIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/': {
      id: '/dashboard/account/'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/transaction/create': {
      id: '/dashboard/transaction/create'
      path: '/transaction/create'
      fullPath: '/dashboard/transaction/create'
      preLoaderRoute: typeof DashboardTransactionCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/product/create': {
      id: '/dashboard/product/create'
      path: '/product/create'
      fullPath: '/dashboard/product/create'
      preLoaderRoute: typeof DashboardProductCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/create': {
      id: '/dashboard/platform-product/create'
      path: '/platform-product/create'
      fullPath: '/dashboard/platform-product/create'
      preLoaderRoute: typeof DashboardPlatformProductCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/platform-product/$id': {
      id: '/dashboard/platform-product/$id'
      path: '/platform-product/$id'
      fullPath: '/dashboard/platform-product/$id'
      preLoaderRoute: typeof DashboardPlatformProductIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/create': {
      id: '/dashboard/email/create'
      path: '/email/create'
      fullPath: '/dashboard/email/create'
      preLoaderRoute: typeof DashboardEmailCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/email/$id': {
      id: '/dashboard/email/$id'
      path: '/email/$id'
      fullPath: '/dashboard/email/$id'
      preLoaderRoute: typeof DashboardEmailIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account/create': {
      id: '/dashboard/account/create'
      path: '/account/create'
      fullPath: '/dashboard/account/create'
      preLoaderRoute: typeof DashboardAccountCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAccountCreateRoute: typeof DashboardAccountCreateRoute
  DashboardEmailIdRoute: typeof DashboardEmailIdRoute
  DashboardEmailCreateRoute: typeof DashboardEmailCreateRoute
  DashboardPlatformProductIdRoute: typeof DashboardPlatformProductIdRoute
  DashboardPlatformProductCreateRoute: typeof DashboardPlatformProductCreateRoute
  DashboardProductCreateRoute: typeof DashboardProductCreateRoute
  DashboardTransactionCreateRoute: typeof DashboardTransactionCreateRoute
  DashboardAccountIndexRoute: typeof DashboardAccountIndexRoute
  DashboardEmailIndexRoute: typeof DashboardEmailIndexRoute
  DashboardLogsIndexRoute: typeof DashboardLogsIndexRoute
  DashboardPlatformProductIndexRoute: typeof DashboardPlatformProductIndexRoute
  DashboardProductIndexRoute: typeof DashboardProductIndexRoute
  DashboardTransactionIndexRoute: typeof DashboardTransactionIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAccountCreateRoute: DashboardAccountCreateRoute,
  DashboardEmailIdRoute: DashboardEmailIdRoute,
  DashboardEmailCreateRoute: DashboardEmailCreateRoute,
  DashboardPlatformProductIdRoute: DashboardPlatformProductIdRoute,
  DashboardPlatformProductCreateRoute: DashboardPlatformProductCreateRoute,
  DashboardProductCreateRoute: DashboardProductCreateRoute,
  DashboardTransactionCreateRoute: DashboardTransactionCreateRoute,
  DashboardAccountIndexRoute: DashboardAccountIndexRoute,
  DashboardEmailIndexRoute: DashboardEmailIndexRoute,
  DashboardLogsIndexRoute: DashboardLogsIndexRoute,
  DashboardPlatformProductIndexRoute: DashboardPlatformProductIndexRoute,
  DashboardProductIndexRoute: DashboardProductIndexRoute,
  DashboardTransactionIndexRoute: DashboardTransactionIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
