export const TENANT_REPOSITORY = 'TENANT_REPOSITORY';
export const TELE_NOTIFIER_REPOSITORY = 'TELE_NOTIFIER_REPOSITORY';
export const TASK_QUEUE_REPOSITORY = 'TASK_QUEUE_REPOSITORY';
export const EMAIL_REPOSITORY = 'EMAIL_REPOSITORY';
export const PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY';
export const PRODUCT_VARIANT_REPOSITORY = 'PRODUCT_VARIANT_REPOSITORY';
export const PLATFORM_PRODUCT_REPOSITORY = 'PLATFORM_PRODUCT_REPOSITORY';
export const ACCOUNT_REPOSITORY = 'ACCOUNT_REPOSITORY';
export const ACCOUNT_PROFILE_REPOSITORY = 'ACCOUNT_PROFILE_REPOSITORY';
export const ACCOUNT_USER_REPOSITORY = 'ACCOUNT_USER_REPOSITORY';
export const ACCOUNT_MODIFIER_REPOSITORY = 'ACCOUNT_MODIFIER_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
export const TRANSACTION_ITEM_REPOSITORY = 'TRANSACTION_ITEM_REPOSITORY';
export const REVENUE_STATISTICS_REPOSITORY = 'REVENUE_STATISTICS_REPOSITORY';
export const PRODUCT_SALES_STATISTICS_REPOSITORY
  = 'PRODUCT_SALES_STATISTICS_REPOSITORY';
export const PEAK_HOUR_STATISTICS_REPOSITORY
  = 'PEAK_HOUR_STATISTICS_REPOSITORY';
export const PLATFORM_STATISTICS_REPOSITORY = 'PLATFORM_STATISTICS_REPOSITORY';
export const EMAIL_SUBJECT_REPOSITORY = 'EMAIL_SUBJECT_REPOSITORY';
export const SYSLOG_REPOSITORY = 'SYSLOG_REPOSITORY';
