[app]
name = "Testing Bot 2"
max_concurrent_tasks = 5
task_timeout_ms = 300000
# api_base_url = "https://api.volve-capital.com"
api_base_url = "http://127.0.0.1:5000"

[api]
app_id = "paytronik"
app_secret = "f220c1a051ec9e90def1e3a1d90df9b0"

[connector]
enabled = true

[logger]
level = "info"

[[modules]]
module = "shopee-order"
name = "paytronik"
recycle_interval = 30
loginKey = "anangg628@gmail.com"
password = "Jogokariyan78"
message_before = [
"""
❗️RULES NTFLIX (WAJIB BACA)❗️

1. Hanya untuk 1 Device (ganti device tidak ada garansi)
2. Dilarang Mengubah/menggunakan profile yang bukan miliknya
3. Dilarang Mengubah Apapun (termasuk pin, nama profile dan password)
4. Melanggar :  GARANSI HANGUS
"""
]
message_after = [
"""
Tolong Bantu Ulasan bintang 5 ya kak :) ⭐️⭐️⭐️⭐️⭐

--------THANK YOU--------
"""
]
message_fallback = "Pesanan kaka sudah kami terima dan akan kami proses segera, mohon ditunggu 🔁"

[[modules]]
module = "shopee-order"
name = "digital_premium"
recycle_interval = 30
loginKey = "digitalpremium.id"
password = "Bintang78"
message_before = [
"""
❗️RULES NTFLIX (WAJIB BACA)❗️

1. Hanya untuk 1 Device (ganti device tidak ada garansi)
2. Dilarang Mengubah/menggunakan profile yang bukan miliknya
3. Dilarang Mengubah Apapun (termasuk pin, nama profile dan password)
4. Melanggar :  GARANSI HANGUS
"""
]
message_after = [
"""
Tolong Bantu Ulasan bintang 5 ya kak :) ⭐️⭐️⭐️⭐️⭐

--------THANK YOU--------
"""
]
message_fallback = "Pesanan kaka sudah kami terima dan akan kami proses segera, mohon ditunggu 🔁"

[[modules]]
module = "shopee-order"
name = "papapremium"
recycle_interval = 30
loginKey = "papapremium"
password = "Baguvix123"
message_before = [
"""
❗️RULES NTFLIX (WAJIB BACA)❗️

1. Hanya untuk 1 Device (ganti device tidak ada garansi)
2. Dilarang Mengubah/menggunakan profile yang bukan miliknya
3. Dilarang Mengubah Apapun (termasuk pin, nama profile dan password)
4. Melanggar :  GARANSI HANGUS
"""
]
message_after = [
"""
Tolong Bantu Ulasan bintang 5 ya kak :) ⭐️⭐️⭐️⭐️⭐

--------THANK YOU--------
"""
]
message_fallback = "Pesanan kaka sudah kami terima dan akan kami proses segera, mohon ditunggu 🔁"

#[[modules]]
#module = "netflix"
#name = "netflix"
